name: Cron jobs
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches: [master]

jobs:
  affiliate:
    name: Affiliate program
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [test, production]

    steps:
      - run: curl --silent --show-error --fail "https://affiliate.swingby.network/api/$MODE/earners/process?secret=$API_SECRET"
        timeout-minutes: 2
        env:
          API_SECRET: ${{ secrets.AFFILIATE_API_SECRET }}
          MODE: ${{ matrix.mode }}

  network-api-generic:
    name: Skybridge network
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [ips]

    steps:
      - run: curl --silent --show-error --fail "https://network.skybridge.exchange/api/v3/process/$TASK?secret=$API_SECRET"
        timeout-minutes: 2
        env:
          API_SECRET: ${{ secrets.NETWORK_API_SECRET }}
          TASK: ${{ matrix.task }}

  network-api-with-mode-and-bridge:
    name: Skybridge network
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [test, production]
        bridge: [btc_erc, btc_bep20]
        task: ["active-nodes", peers, churns]

    steps:
      - run: curl --silent --show-error --fail "https://network.skybridge.exchange/api/v3/process/$MODE/$BRIDGE/$TASK?secret=$API_SECRET"
        timeout-minutes: 2
        env:
          API_SECRET: ${{ secrets.NETWORK_API_SECRET }}
          MODE: ${{ matrix.mode }}
          BRIDGE: ${{ matrix.bridge }}
          TASK: ${{ matrix.task }}

  metanodes-generic:
    name: Metanodes API (generic)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - run: curl --silent --show-error --fail "https://metanode-earnings.vercel.app/api/v1/process/vwap-prices?secret=$API_SECRET"
        timeout-minutes: 2
        env:
          API_SECRET: ${{ secrets.METANODES_API_SECRET }}
      - run: curl --silent --show-error --fail "https://metanode-earnings.vercel.app/api/v1/process/production/bonds?secret=$API_SECRET"
        timeout-minutes: 2
        env:
          API_SECRET: ${{ secrets.METANODES_API_SECRET }}
      - run: curl --silent --show-error --fail "https://metanode-earnings.vercel.app/api/v1/process/test/bonds?secret=$API_SECRET"
        timeout-minutes: 2
        env:
          API_SECRET: ${{ secrets.METANODES_API_SECRET }}

  metanodes-matrix:
    name: Metanodes API
    needs: metanodes-generic
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [testnet, production]
        bridge: [btc_erc, btc_bep20]
        task: [rewards, churns, "active-nodes", floats]

    steps:
      - run: curl --silent --show-error --fail "https://metanode-earnings.vercel.app/api/v1/process/$MODE/$BRIDGE/$TASK?secret=$API_SECRET"
        timeout-minutes: 2
        env:
          API_SECRET: ${{ secrets.METANODES_API_SECRET }}
          MODE: ${{ matrix.mode }}
          BRIDGE: ${{ matrix.bridge }}
          TASK: ${{ matrix.task }}

  graph:
    name: GraphQL API
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: ["testnet.", ""]
        bridge: [btc_erc, btc_bep20]
        task:
          - "swaps-and-withdrawals/latest"
          - "swaps-and-withdrawals/pending"
          - "deposits/latest"
          - "deposits/pending"
          - nodes

    steps:
      - run: curl --silent --show-error --fail "https://${MODE}graph.skybridge.info/api/v1/$BRIDGE/process/$TASK?secret=$API_SECRET"
        timeout-minutes: 2
        env:
          API_SECRET: ${{ secrets.GRAPH_API_SECRET }}
          MODE: ${{ matrix.mode }}
          BRIDGE: ${{ matrix.bridge }}
          TASK: ${{ matrix.task }}

  swingby-bridge:
    name: Swingby Bridge
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: [ethereum, goerli, bsc, bsct]
        task: [deposits, payments, pending-payments, failed-payments]

    steps:
      - run: curl --silent --show-error --fail "https://bridge.swingby.network/api/v1/process/$NETWORK/$TASK?secret=$API_SECRET"
        timeout-minutes: 2
        env:
          API_SECRET: ${{ secrets.SWINGBY_BRIDGE_API_SECRET }}
          NETWORK: ${{ matrix.network }}
          TASK: ${{ matrix.task }}
